include:
  - board: xiao_ble
    shield: totem_left
    artifact-name: totem_central_left
  - board: xiao_ble
    shield: totem_right
    artifact-name: totem_peripheral_right
# there is no settingsreset (needed) for the XIAO
